development:
  adapter: postgresql
  encoding: unicode
  database: events_development
  pool: 5
  username: events
  password:
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: events_test
  pool: 5
  username: events
  password:
  host: localhost
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: events_production
  pool: 5
  username: events
  password:
